version: '3.7'
services:
  bot:
    build: .
    restart: always
    command: sh -c "python -m bot"
    env_file:
      - ./.env

    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
